<h2><u> 1. Polyphormism

* 1.method overloading
* 2.method overriding
* 3.operator overloading

<h4> <li> Method overloading 

* compile time polyphormism
* it occurs in same class
* methods must have same name and different parameter
* python does not suppport method overloading


<h4> <li> Method overriding 

* runtime time polyphormism
* it occurs in two class via inheritence
* methods must have same name and same parameter
* python suppport method overriding


In [2]:
class A:
    def add(self,a,b):
        print(a+b)
        
    def add(self,a,b,c=0):
        print(a+b+c)
        
obj=A()
obj.add(10,20)
obj.add(10,20,30)

30
60


In [4]:
class A:
    def first(self):
        print("First function of class A")
        
    def second(self):
        print("Second function of class A")
        
class B(A):
    def first(self):
        print("First function of class B")
        
    def display(self):
        print("Display function of class B")
        
obj=B()
obj.first()
obj.second()
obj.display()
print()

obj1=A()
obj1.first()
obj1.second()
# obj1.display() AttributeError: 'A' object has no attribute 'display'

First function of class B
Second function of class A
Display function of class B

First function of class A
Second function of class A


In [10]:
class parent:
    def __init__(self):
        self.attr1=50
        self.attr2=60
        
class child(parent):
    def __init__(self):
        self.attr3=70
        super().__init__()
    #         OR
    #   parent.__init__(self)

obj=child()
print(obj.attr1)

50


In [2]:
class Add:
    def result(self,a,b):
        print("Adddition",a+b)
        
class Multi(Add):
    def result(self,a,b):
        super().result(a,b)
        print("Multiplication",a*b)
        
m=Multi()
m.result(10,20)
m=Add()
m.result(10,20)

Adddition 30
Multiplication 200
Adddition 30


<h4> <li> Operator overloading

In [4]:
# + --> __add__(self,other)
# - --> __sub__(self,other)
# * --> __mul__(self,other)
# / --> __truediv__(self,other)
# // --> __floordiv__(self,other)
# % --> __mod__(self,other)
# ** --> __pow__(self,other)

# >  --> __gt__(self,other)
# <  --> __lt__(self,other)
# >= --> __ge__(self,other)
# <= --> __le__(self,other)
# == --> __eq__(self,other)
# != --> __ne__(self,other)

In [21]:
class A:
    def __init__(self,a):
        self.a=a
        
    def __add__(self,other):
        return self.a+other.a

    def  __sub__(self,other):
        return self.a-other.a
    
    def  __mul__(self,other):
        return self.a*other.a
    
    def __truediv__(self,other):
        return self.a/other.a
    
    def __floordiv__(self,other):
        return self.a//other.a
    
    def __mod__(self,other):
        return self.a%other.a
    
    def __pow__(self,other):
        return self.a**other.a
    
    def __gt__(self,other):
        return self.a>other.a
    
    def __lt__(self,other):
        return self.a<other.a
    
    def __ge__(self,other):
        return self.a>=other.a
    
    def  __le__(self,other):
        return self.a<=other.a
    
    def __eq__(self,other):
        return self.a==other.a
    
    def __ne__(self,other):
        return self.a!=other.a

obj1=A(2)
obj2=A(3)
obj3=A("Hi")
obj4=A("Hello")
obj5=A(3)
obj6=A(5)

print("ADD: ",obj1+obj2)
print("ADD: ",obj3+obj4)
print("SUB:",obj1-obj2)
print("MUL:",obj1*obj2)
print("MUL:",obj3*obj2)
print("DIV:",obj2/obj1)
print("FLOOR DIV:",obj2//obj1)
print("MOD:",obj1%obj2)
print("POW:",obj1**obj2)

print("Comparison Operator: ")
print("GT:",obj5>obj2)
print("LT:",obj6<obj2)
print("GE:",obj5>=obj2)
print("LE:",obj1<=obj2)
print("EQ:",obj5==obj2)
print("NE:",obj5!=obj2)
print(obj5.__add__(obj1))

ADD:  5
ADD:  HiHello
SUB: -1
MUL: 6
MUL: HiHiHi
DIV: 1.5
FLOOR DIV: 1
MOD: 2
POW: 8
Comparison Operator: 
GT: False
LT: False
GE: True
LE: True
EQ: True
NE: False
5


<h2><u> 2. Single Inheritance

<h4> I. Single Inheritance

In [23]:
class parent:
    def func1(self):
        print("Hello Parent")

class child(parent):
    def func2(self):
        print("Hello child")
        
test=child()
test.func1()
test.func2()

Hello Parent
Hello child


<h4> II. Multiple Inheritance

In [36]:
class parent1:
    def func1(self):
        print("Hello parent1")
        
class parent2:
    def func2(self):
        print("Hello parent2")
        
class parent3:
    def func2(self):
        print("Hello parent3")
        
class child(parent1,parent3,parent2):
    def func3(self):
        print("Hello Child")
        
test=child()
test.func1()
test.func2()
test.func3()

# Method Resolution order
print(child.__mro__) 
print(child.mro())
print(parent2.mro())

Hello parent1
Hello parent3
Hello Child
(<class '__main__.child'>, <class '__main__.parent1'>, <class '__main__.parent3'>, <class '__main__.parent2'>, <class 'object'>)
[<class '__main__.child'>, <class '__main__.parent1'>, <class '__main__.parent3'>, <class '__main__.parent2'>, <class 'object'>]
[<class '__main__.parent2'>, <class 'object'>]


<h4> III. Multilevel Inheritance

In [42]:
class grandparent:
    def property0(self):
        print("plot in village")

class parent(grandparent):
    def property1(self):
        print("Flat in city")
        
class child(parent):
    def property2(self):
        print("Debt of Home loan")
        
obj1=child()
print(child.mro())
print(parent.mro())
obj1.property0()


[<class '__main__.child'>, <class '__main__.parent'>, <class '__main__.grandparent'>, <class 'object'>]
[<class '__main__.parent'>, <class '__main__.grandparent'>, <class 'object'>]
plot in village


<h4> IV. Hierarchical Inheritance

In [54]:
class parent:
    s=10000

class son(parent):
    def property1(self):
        print(self.s*0.7)

class daughter(parent):
    def property2(self):
        print(self.s*0.2)
    
obj2=daughter()
obj1=son()

obj1.property1()
obj2.property2()

7000.0
2000.0


<h4> V. Hybrid Inheritance

In [59]:
class parent1:
    def func1(self):
        print("Hello Parent1")
        
class parent2:
    def func2(self):
        print("Hello Parent2")
        
class child1(parent1):
    def func3(self):
        print("Hello child1")
        
class child2(child1,parent2):
    def func4(self):
        print("Hello child2")
        
test1=child1()
test2=child2()
test1.func1()
test1.func3()

test2.func1()
test2.func2()
test2.func3()
test2.func4()
print(child1.mro())
print(child2.mro())

Hello Parent1
Hello child1
Hello Parent1
Hello Parent2
Hello child1
Hello child2
[<class '__main__.child1'>, <class '__main__.parent1'>, <class 'object'>]
[<class '__main__.child2'>, <class '__main__.child1'>, <class '__main__.parent1'>, <class '__main__.parent2'>, <class 'object'>]


<h2> <li type="disc">  issubclass()

In [5]:
class parent():
    def function1():
        print("Hello")
        
class child(parent):
    def function2():
        print("Hello child")

print(issubclass(child,parent))
print(issubclass(parent,child))

True
False


<h2> <li type="disc">  isinstance()

In [4]:
class parent():
    def function1():
        print("Hello")
        
class child(parent):
    def function2():
        print("Hello child")

A=child()
B=parent()
print(isinstance(A,child))
print(isinstance(A,parent))
print(isinstance(B,child))
print(isinstance(B,parent))

True
True
False
True


<h2> <li type="disc">   Method Resolution order

In [7]:
# Method Resolution order

class A:
    def rk(self):
        print("in class A")
        
class B(A):
    def rk(self):
        print("in class B")
        
class C(A):
    def rk(self):
        print("in class C")
        
class D(B,C):
    pass

r=D()
r.rk()
print(D.mro())

in class B
[<class '__main__.D'>, <class '__main__.B'>, <class '__main__.C'>, <class '__main__.A'>, <class 'object'>]


In [19]:
class P1:
    def foo(self):
        print("Foo from P1")
        
class P2:
    def foo(self):
        print("Foo from P2")
        
    def bar(self):
        print("Bar from P2")
        
class C1(P1):
    pass

class C2(P2):
    pass

class GC(C1,C2):
    pass

g=GC()
g.foo()
g.bar()
print(GC.mro())

Foo from P1
Bar from P2
[<class '__main__.GC'>, <class '__main__.C1'>, <class '__main__.P1'>, <class '__main__.C2'>, <class '__main__.P2'>, <class 'object'>]


In [26]:
class A:pass
class B:pass
class C:pass
class D:pass
class E:pass
class K1(C,A,B):pass
class K3(A,D):pass
class K2(B,D,E):pass
class Z(K1,K3,K2):pass
print(Z.mro())


[<class '__main__.Z'>, <class '__main__.K1'>, <class '__main__.C'>, <class '__main__.K3'>, <class '__main__.A'>, <class '__main__.K2'>, <class '__main__.B'>, <class '__main__.D'>, <class '__main__.E'>, <class 'object'>]


In [30]:
class A:pass
class B:pass
class C:pass
class D:pass
class E:pass
class K1(C,A,B):pass
class K3(A,D):pass
class K2(B,D,E):pass
class Z(K1,K2,K3):pass
print(Z.mro())


[<class '__main__.Z'>, <class '__main__.K1'>, <class '__main__.C'>, <class '__main__.K2'>, <class '__main__.K3'>, <class '__main__.A'>, <class '__main__.B'>, <class '__main__.D'>, <class '__main__.E'>, <class 'object'>]


<h2> <li type="disc"><u>   Abstraction

In [4]:
from abc import ABC,abstractmethod

class Shape(ABC):
    def __init__(self,shape_name):
        self.shape_name=shape_name
        
    @abstractmethod
    def draw(self):
        pass
    
class Circle(Shape):
    def __init__(self):
        super().__init__("Circle")
        
    def draw(self):
        print("Drawing a",self.shape_name)
        
c=Circle()
c.draw()

Drawing a Circle


In [20]:
class Staff:
    def __init__(self,name,salary):
        self.name=name
        self.salary=salary
        
    def display(self):
        print("Name:",self.name,"\nSalary:",self.salary)
        
class Teaching(Staff):
    def __init__(self,name,salary,subject):
#         super().__init__(input("Ente name:"),input("Enter salary:"))
        self.name=name
        self.salary=salary
        self.subject=subject
        
    def display(self):
        super().display()
        print("Subject:",self.subject)
        
class Non_Teaching(Staff):
    def __init__(self,name,salary,dept):
#         super().__init__(input("Ente name:"),input("Enter salary:"))
        self.name=name
        self.salary=salary
        self.dept=dept
        
    def display(self):
        super().display()
        print("Department:",self.dept)
        
t=Teaching("Meet",10000,"JAVA")
t.display()      
print()
nt=Non_Teaching("Meet",10000,"BE")
nt.display()        

Name: Meet 
Salary: 10000
Subject: JAVA

Name: Meet 
Salary: 10000
Department: BE


In [21]:
# Create a class called as Student having name and email as its data member and put_data as bound method.
# The __init__ function should used to pass variable and the put_data function should display the data member.
# Create another class called PHD_guide having name,email,students as its data member ,
# here the student varaible is the list of student under the guide.
# The PHD_guide should have four Bound method:__init__,put_data,add,remove
#
#__init__:to intialise data
# put_data :should display data member including list of student
# add:Should add student to the student list
# remove:should remove student from the list

In [32]:
class Student:
    def __init__(self,name,email):
        self.name=name
        self.email=email
    
    def put_data(self):
        print("Name:",self.name)
        print("Email:",self.email)
        
class PHD_Guide(Student):
    def __init__(self,name,email):
        self.s=[]
        self.name=name
        self.email=email
        
    def put_data(self):
        super().put_data()
        print("Students:",self.s)
        
    def add(self):
        self.s.append(input("Enter name:"))
        
    def remove(self):
        t=input("Enter name:")
        
        if t in self.s:
            self.s.remove(t)
        else:
            print("No such student found!!")
            
p=PHD_Guide("Meet","meet272005@gmail.com")
p.put_data()
p.add()
p.add()
p.add()
p.put_data()
p.remove()
p.remove()   
p.put_data()

Name: Meet
Email: meet272005@gmail.com
Students: []
Enter name:Eminem
Enter name:2PAC
Enter name:Drake
Name: Meet
Email: meet272005@gmail.com
Students: ['Eminem', '2PAC', 'Drake']
Enter name:Weekend
No such student found!!
Enter name:Drake
Name: Meet
Email: meet272005@gmail.com
Students: ['Eminem', '2PAC']


In [33]:
# Create a class student with the following member attributes :
    # Roll
    # Name
    # Age
    # Total marks
# Create suitable methods for reading and printing member variable.
# WAP to overload == operator to print the details of students having same marks

In [39]:
class Student:
    def __init__(self,rollno,name,age,marks):
        self.rollno=rollno
        self.name=name
        self.age=age
        self.marks=marks
        
    def display(self):
        print("\n----------------")
        print("Roll no:",self.rollno)
        print("Name:",self.name)
        print("Age",self.age)
        print("Marks:",self.marks)
        print("----------------")
        
        
    def __eq__(self,other):
        self.display()
        other.display()

s1=Student(55,"Meet",20,58)
s2=Student(39,"Divy",19,68)
s3=Student(71,"Manasvi",19,58)

s1.display()
s2.display()
s3.display()
s1==s2
s2==s3


----------------
Roll no: 55
Name: Meet
Age 20
Marks: 58
----------------

----------------
Roll no: 39
Name: Divy
Age 19
Marks: 68
----------------

----------------
Roll no: 71
Name: Manasvi
Age 19
Marks: 58
----------------

----------------
Roll no: 55
Name: Meet
Age 20
Marks: 58
----------------

----------------
Roll no: 39
Name: Divy
Age 19
Marks: 68
----------------

----------------
Roll no: 39
Name: Divy
Age 19
Marks: 68
----------------

----------------
Roll no: 71
Name: Manasvi
Age 19
Marks: 58
----------------


In [1]:
# WAP to find net salary of employee using inheritance create three class:
# 1.Employee (Abstract class):
#     1.1 getEmployee: it takes user input for id,name,basic salary
#     1.2 EmployeeDetails: print id,name,basic salary
#     1.3 getSalary: return a basic salary
#     1.4 emp_id : abstract method

# 2.Perks:
#     2.1 calculatePerks: calculate DA,HRA,PF
#             DA:35% of basic salary
#             HRA:17% of basic salary
#             PF:12% of basic salary
#     2.2 printPerks: print DA,HRA,PF
#     2.3 totalPerks: return DA+HRA-PF
#     2.4 emp_id: due to abstraction

# 3.NetSalary:
#     3.1 getSalary :Calculate total Salary


In [4]:
from abc import *

class Employee(ABC):
    def getEmployee(self):
        self.id=int(input("Enter id:"))
        self.name=input("Enter name:")
        self.basicSalary=int(input("Enter basic salary:"))
        
    
    def EmployeeDetails(self):
        print("ID :",self.id)
        print("Name :",self.name)
        print("Basic Salary :",self.basicSalary)
    
    def getSalary(self):
        return self.basicSalary
    
    @abstractmethod
    def emp_id(self):
        pass

class Perks(Employee):
    def calculatePerks(self):
        self.DA=self.basicSalary*0.35
        self.HRA=self.basicSalary*0.17
        self.PF=self.basicSalary*0.12
    
    def printPerks(self):
        print("DA :",self.DA)
        print("HRA :",self.HRA)
        print("PF :",self.PF)
    
    def totalPerks(self):
        self.totalPerks=self.DA+self.HRA- self.PF
        return self.totalPerks
        
    def emp_id(self):
        pass
    
class NetSalary(Perks):
    def getTotal(self):
        return self.basicSalary+self.totalPerks
    
Emp1=NetSalary()
Emp1.getEmployee()
Emp1.EmployeeDetails()
print(Emp1.getSalary())
Emp1.calculatePerks()
Emp1.printPerks()
print(Emp1.totalPerks())
print(Emp1.getTotal())

Enter id:101
Enter name:Meet
Enter basic salary:550000
ID : 101
Name : Meet
Basic Salary : 550000
550000
DA : 192500.0
HRA : 93500.0
PF : 66000.0
220000.0
770000.0


In [18]:
class Bill:
    def __init__(self):
        self.products={"HDD":5000,"RAM":2000,"Printer":6000,"Pendrive":800}
        self.cart={}
        self.price=0
        for i,j in self.products.items():
            print(i," at RS.",j)
            print("Want this is item ? (Yes/NO)")
            ans=input("Enter answer: ").lower()
            if ans=="yes":
                quantity=int(input("Enter quantity:"))
                self.cart[i]=j*quantity
        for i in self.cart.values():
            self.price=self.price+i
        print("Total Amount:",self.price)
        print('''Payment options:
                   1.Cash Payment
                   2.Cheque Payment''')
        option=int(input("Select Options: "))
        if option==1:
            Cash=CashPayment(self.price)
        elif option==2:
            Cash=ChequePayment()
        else:
            print("wrong input")
        
        
class CashPayment(Bill):
    def __init__(self,price):
        self.price=price
        self.d={2000:0,500:0,200:0,100:0,50:0,20:0,10:0}
        for i,j in self.d.items():
            self.d[i]=self.price//i
            self.price=self.price-((self.price//i)*i)
            if self.price==0:
                break
            
        for i,j in self.d.items():
            if j!=0:
                print("No of",i,"Notes:",j)
                
class ChequePayment(Bill):
    def __init__(self):
        self.acc=input("Enter Account no:")
        self.pin=int(input("Enter pin:"))
        print("Payment Successfull")
          
        
buy=Bill()

HDD  at RS. 5000
Want this is item ? (Yes/NO)
Enter answer: yes
Enter quantity:1
RAM  at RS. 2000
Want this is item ? (Yes/NO)
Enter answer: yes
Enter quantity:3
Printer  at RS. 6000
Want this is item ? (Yes/NO)
Enter answer: no
Pendrive  at RS. 800
Want this is item ? (Yes/NO)
Enter answer: yes
Enter quantity:7
Total Amount: 16600
Payment options:
                   1.Cash Payment
                   2.Cheque Payment
Select Options: 1
No of 2000 Notes: 8
No of 500 Notes: 1
No of 100 Notes: 1


<h2> <li type="disc"><u>   Numpy

* Numerical Python
* Python Library used for warning with arrays.
* Created in 2005 by Travis oliphant.
* list that serves the purpose of arrays,but slow to process.
* Numpy aims to provide an array object that is upto 50x faster than tradional pyhton list.

In [1]:
import numpy as np
import sys

s=range(1000)
print("size of each element of list in byte:",sys.getsizeof(s))
print("size of whole list in bytes:",sys.getsizeof(s)*len(s))

d=np.arange(1000)
print("size of each element of numpy array in byte:",d.itemsize)
print("size of whole numpy array in bytes:",d.itemsize*d.size)

size of each element of list in byte: 48
size of whole list in bytes: 48000
size of each element of numpy array in byte: 4
size of whole numpy array in bytes: 4000


In [7]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)
arr=np.array([[[1,2,3,4,5]]])
print(arr.ndim)
print(type(arr))
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1:2,0:3])
print(arr[1,0:3])
print(arr[0:2,2])

[1 2 3 4 5]
1
3
<class 'numpy.ndarray'>
[[5 6 7]]
[5 6 7]
[3 7]


In [28]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
arr4=np.array([1,2,3,4,5],ndmin=5)

print(arr1.ndim)
print(arr1.shape)

print(arr2.ndim)
print(arr2.shape)

print(arr3.ndim)
print(arr3.shape)
print(arr4)
print(arr4.shape)

newarr=arr1.reshape(3,-1)
print(newarr.base)
print(newarr)

for x in np.nditer(newarr):
    print(x)
    
print()

for x in np.nditer(arr2[0:1,::2]):
    print(x)

print()
    

1
(6,)
2
(2, 4)
3
(1, 4, 3)
[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
1
2
3
4
5
6

1
3


<h2> <li type="disc"><u>   Built in function

In [45]:
#  1. Concatenate

import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.concatenate((arr1,arr2,arr3),axis=0)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [50]:
import numpy as np

arr1=np.array([[1,2],[3,0]])
arr2=np.array([[4,5],[6,0]])
arr3=np.array([[7,8],[9,0]])
arr=np.concatenate((arr1,arr2,arr3),axis=0)
print(arr)
print(arr.shape)
arr=np.concatenate((arr1,arr2,arr3),axis=1)
print(arr)
print(arr.shape)

[[1 2]
 [3 0]
 [4 5]
 [6 0]
 [7 8]
 [9 0]]
(6, 2)
[[1 2 4 5 7 8]
 [3 0 6 0 9 0]]
(2, 6)


In [61]:
#  2.Split

import numpy as np

arr=np.array([1,2,3,4])
newarr=np.array_split(arr,3)
print(newarr)
newarr=np.array_split(arr,4)
print(newarr)
newarr=np.array_split(arr,5)
print(newarr)


arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
newarr=np.array_split(arr1,3)
print(newarr)
newarr=np.array_split(arr1,4,axis=1)
print(newarr)

[array([1, 2]), array([3]), array([4])]
[array([1]), array([2]), array([3]), array([4])]
[array([1]), array([2]), array([3]), array([4]), array([], dtype=int32)]
[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]])]
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]


In [3]:
# 3. Where

import numpy as np
arr=np.array([1,2,3,4,5,6,4])
x=np.where(arr==4)
print(x)
x=np.where(arr%2==0)
print(x)

arr=np.array([[1,2],[3,4],[4,5],[7,8]])
x=np.where(arr==4)
print(x)

arr=np.array([[[1,2,3],[4,5,3]],[[3,4,6],[7,3,2]]])
x=np.where(arr==3)
print(x)

(array([3, 6], dtype=int64),)
(array([1, 3, 5, 6], dtype=int64),)
(array([1, 2], dtype=int64), array([1, 0], dtype=int64))
(array([0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1], dtype=int64), array([2, 2, 0, 1], dtype=int64))


In [41]:
#  4.sort()

import numpy as np

arr1=np.array([1,2,3,4,5,4,6,7])
print(np.sort(arr1))

arr2=np.array(['banana','apple','cherry'])
print(np.sort(arr2))

arr3=np.array([True,False,True])
print(np.sort(arr3),end="\n\n")

arr4=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr4),end="\n\n")

arr5=np.sort(arr4,axis=1)
print(arr5,end="\n\n")
print(np.sort(arr5,axis=0),end="\n\n")
print(np.sort(arr5,axis=None))

arr6=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
print(np.sort(arr6,axis=-1),end="\n\n")
print(np.sort(arr6,axis=0),end="\n\n")

[1 2 3 4 4 5 6 7]
['apple' 'banana' 'cherry']
[False  True  True]

[[2 3 4]
 [1 3 7]
 [2 4 5]]

[[2 3 4]
 [1 3 7]
 [2 4 5]]

[[1 3 4]
 [2 3 5]
 [2 4 7]]

[1 2 2 3 3 4 4 5 7]
[[[2 3 8]
  [3 7 9]]

 [[2 6 7]
  [4 6 9]]]

[[[3 2 2]
  [7 6 3]]

 [[6 7 8]
  [9 9 4]]]

